### ISSUE TITLE
Re-naming

### ISSUE THREAD

**Issue by dfm** [afeinstein20/ELLIE#19]
When we re-name the project to `elanor`, we'll need to do it in a few places and it'll probably break things. First, we'll have to change `ellie` to `elanor` in a few places in `setup.py`. Then we'll need to rename the `ellie` directory to `elanor`. I think that it would also be good to rename the git repo, but I'm cool either way with that one.

**Comment by dfm** [comment]
Also: `eleanor` because I'm bad a spelling.

**Comment by afeinstein20** [comment]
We could rename the `ellie` directory to `eleanor` which would allow us to do `import eleanor as ellie` or we could leave it as is and the import would be `from eleanor import ellie`. Seems like a stylistic choice to me that I don't have strong opinions about!

**Comment by dfm** [comment]
If we don't rename the directory then it'll actually be:

```bash
pip install eleanor
```

then:

```python
import ellie
```

which I think would be confusing so I think we must rename the directory.

**Comment by afeinstein20** [comment]
Ok! I renamed the directory to `eleanor`
